apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manual
provisioner: kubernetes.io/no-provisioner  # This is used for local PVs like hostPath
volumeBindingMode: WaitForFirstConsumer  # This is recommended for local PVs
